package com.hashkey.trackme;

import android.app.Activity;
import android.app.ProgressDialog;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.telephony.SmsManager;
import android.util.Log;
import android.view.View;
import android.widget.EditText;
import android.widget.Toast;

import com.parse.GetCallback;
import com.parse.ParseException;
import com.parse.ParseGeoPoint;
import com.parse.ParseObject;
import com.parse.ParseQuery;

public class Find extends Activity {

	private EditText phoneNo = null;
	ProgressDialog dialog;
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_find);
		phoneNo = (EditText) findViewById(R.id.phone_number_find_edit_text);
	}
	
	private Double lat = null;
	private Double lng = null;
	public void onCloudClicked(View view){
		dialog = ProgressDialog.show(this, "", "Awaiting Data from Cloud...", true);
		String phoneNumber = phoneNo.getText().toString().trim();
		if(phoneNumber == "" || phoneNumber == null){
			Toast.makeText(getApplicationContext(), "Please Check the number.", Toast.LENGTH_SHORT).show();
			return;
		}
		Log.d("MINE",phoneNumber);
		ParseQuery<ParseObject> query = ParseQuery.getQuery("LocationData");
		query.whereEqualTo("userId", phoneNumber);
		query.getFirstInBackground(new GetCallback<ParseObject>() {
			  public void done(ParseObject object, ParseException e) {
				  dialog.dismiss();
			    if (object == null) {
			      Log.d("MINE", "The getFirst request failed.");
			      Toast.makeText(getApplicationContext(), "Can't get the location. Check the number.", Toast.LENGTH_SHORT).show();
			    } else {
			    	ParseGeoPoint geoPoint = (ParseGeoPoint) object.get("location");
			    	lat = geoPoint.getLatitude();
			    	lng = geoPoint.getLongitude();
			    	Log.d("MINE", "location: "+geoPoint.getLatitude()+geoPoint.getLongitude());
			    	String labelLocation = "Tracking...";
			    	Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse("geo:<" + lat  + ">,<" + lng + ">?q=<" + lat  + ">,<" + lng + ">(" + labelLocation + ")"));
			    	startActivity(intent);
			    }
			  }
			});
	}
	
	public void onGoClicked(View view){
		String phoneNumber = phoneNo.getText().toString().trim();
//		if (phoneNumber.length() < 10){
//			Toast.makeText(getApplicationContext(), "Check the number.", Toast.LENGTH_SHORT).show();
//			return;
//		}
		phoneNumber = "8861967671";
		String message = "#TrackMe#\nINITIALIZE\nThis message was auto-generated by 'TrackMe'";
		SmsManager smsManager = SmsManager.getDefault();
		smsManager.sendTextMessage(phoneNumber, null, message, null, null);
		Toast.makeText(getApplicationContext(), "Sending SMS... Awaiting Response...", Toast.LENGTH_SHORT).show();
	}
}
