package com.hashkey.trackme;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.telephony.SmsManager;
import android.telephony.SmsMessage;
import android.util.Log;
import android.widget.Toast;

public class SMSTrackReceiver extends BroadcastReceiver {
	// Get the object of SmsManager
	final SmsManager sms = SmsManager.getDefault();

	@Override
	public void onReceive(Context context, Intent intent) {
		// Retrieves a map of extended data from the intent.
		final Bundle bundle = intent.getExtras();
		 
		try {
		     
		    if (bundle != null) {
		         
		        final Object[] pdusObj = (Object[]) bundle.get("pdus");
		         
		        for (int i = 0; i < pdusObj.length; i++) {
		             
		            SmsMessage currentMessage = SmsMessage.createFromPdu((byte[]) pdusObj[i]);
		             
		            String senderNum = currentMessage.getDisplayOriginatingAddress();
		            String message = currentMessage.getDisplayMessageBody();
		            String propInitialise = "#TrackMe#\nINITIALIZE\nThis message was auto-generated by 'TrackMe'";
		            String propLocation = "#TrackMe#\nLOCATION:";
		            String propEmergency = "#TrackMe#\nEMERGENCY:";
		 
		            Log.i("SmsReceiver", "senderNum: "+ senderNum + "; message: " + message);

		            // request to track the host
		            if(message.equalsIgnoreCase(propInitialise)){
		            	Log.d("MINE","got request to initiate tracking");
		            	Intent send = new Intent(context, SendLocation.class);
		            	send.putExtra("phoneNumber", senderNum);
			            context.startService(send);
			            Log.d("MINE","started service");
		            }
		            
		            // receive location data
		            if(message.contains(propLocation) || message.contains(propEmergency)){
		            	Log.d("MINE","recieving data");
		            	String[] lines = message.split(System.getProperty("line.separator"));//3rd line contains the location details as "lat, lng"
		            	Double lat = Double.valueOf(lines[2].split(",")[0]);
		            	Double lng = Double.valueOf(lines[2].split(",")[1]);
		            	Log.d("MINE",""+lat+", "+lng);
		            	String labelLocation = "Latest Location";
		            	Intent maps = new Intent(Intent.ACTION_VIEW, Uri.parse("geo:<" + lat  + ">,<" + lng + ">?q=<" + lat  + ">,<" + lng + ">(" + labelLocation + ")"));
		            	maps.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
				    	context.startActivity(maps);
		            }
		             
		        } // end for loop
		      } // bundle is null
		 
		} catch (Exception e) {
		    Log.e("SmsReceiver", "Exception smsReceiver" +e);
		}
	}

}
